### ISSUE TITLE
Symbols missing from docs

### ISSUE THREAD

**Issue by fenhl** [mtgjson/mtgjson#175]
The documentation of the `text` key on cards refers to the sections `#manaSymbols` and `#otherSymbols`, both of which are dead links.

**Comment by Garbee** [comment]
Symbols were removed to avoid any trademark issues with Wizards. Docs should be updated to remove the links.

**Comment by fenhl** [comment]
Wouldn't it be better to reintroduce the section, and just explaining the textual encoding of the symbols that is used in the JSON, without using the trademarked images?

**Comment by petrblaho** [comment]
Fixed in https://github.com/mtgjson/mtgjson/commit/276a39cee3b75dcbf4877ecb0e8f41e5babacf3b ?

**Comment by fenhl** [comment]
No, symbols are still not documented, and the documentation of the mana cost field is wrong. The real JSON file has costs like `{G}{U}`, not `GU`.

**Comment by fenhl** [comment]
Part of this was fixed in #292. We still need documentation of the mana symbols, even if it's just a reference to the relevant CR section.

**Comment by csuhta** [comment]
The Scryfall team would like to offer this JSON file, if it's at all helpful as a starting point: https://api.scryfall.com/catalog/symbology

Field documentation is here: https://scryfall.com/docs/api-overview#type-card-symbol

**Comment by ZeldaZach** [comment]
We'll be pulling from ScryFall for all icons in our docs in the V4 build
