### ISSUE TITLE
Split cards in pFNM have wrong mciNumber

### ISSUE THREAD

**Issue by MickHardins** [mtgjson/mtgjson#365]
Split cards in pFNM have wrong mcinumber:
Fire / ice : mciNumber = "/79a.html

Same is true for Life / Death

**Comment by silasary** [comment]
Looks like a failing regex.

**Comment by silasary** [comment]
Digging more deeply, it appears that this should have been fixed with bef3f4e6f7fcc2b42e5abf5c62ef13d798ffdf9c (September 2016), but the `MciNumbers` in `pFNM.json` haven't been rebuilt since June 2016 (41ce033eed96c2bb4a2723f6e17e79e10ac6359f).

A rebuild should be enough to fix this.

**Comment by MickHardins** [comment]
Unfortunately, after the latest rebuild #379 the issue is still present.

**Comment by ZeldaZach** [comment]
I figured it would still be. Sounds like a code logic issue.
