### ISSUE TITLE
version.json has wrong date?

### ISSUE THREAD

**Issue by tooomm** [mtgjson/mtgjson#487]
### Steps to reproduce
Go to https://www.mtgjson.com/files/version.json

As of today, you will get:
`{"date": "2019-11-23", "pricesDate": "2019-11-23", "version": "4.6.0+20191123"}`

### What is expected?
There is a `date` and a `pricesDate`. The last one is obvious and correct as it always updates every day.

The first one though is supposed to be the date when card data got updated the last time.
In this case, I would expect it to be the date of the [4.6.0 release](https://mtgjson.com/changelog/#_4-6-0-2019-10-28) which would be `2019-10-28` instead.
Since then only prices got changed every day. No new cards, no typos fixed, no new fields etc.

### What is actually happening?
`date` gets updated every time, the same as `pricesDate`.
While that used to be correct with the old update pattern, this changed with the availability of prices and daily builds to refresh them.
Not every build of the same release to update card prices doesn't mean the release changed or there are new cards, problems fixes or structural changes to the mtgjson file.

<br>

Maybe the wording should change:
`date` or `releaseDate`: date when the version was released
`pricesUpdate`: holds the date of the daily new build
Or remove `pricesDate` completely as the version includes it already...

**Comment by ZeldaZach** [comment]
Daily builds with prices should only update priceDate, not both dates. Fix to be done.

**Comment by ZeldaZach** [comment]
This is a build script issue. Tag @omfgitsmark

**Comment by omfgitsmark** [comment]
Fixed and tested. It will be correct in tomorrow's price build.

**Comment by tooomm** [comment]
Data is still wrong @omfgitsmark 
```
{"date": "2019-12-01", "pricesDate": "2019-12-07", "version": "4.6.1+20191207"}
```

`date` should be "2019-12-04"
At least that's what is written in the [changelog for 4.6.1](https://mtgjson.com/changelog/#_4-6-1).

**Comment by tooomm** [comment]
- 10th December 2019
`{"date": "2019-12-08", "pricesDate": "2019-12-08", "version": "4.6.1+20191208"}`

- 17th December 2019
`{"date": "2019-12-15", "pricesDate": "2019-12-15", "version": "4.6.1+20191215"}`

**Comment by tooomm** [comment]
@omfgitsmark while it's better now and no longer the same value, it's still wrong as of today (22th of december):
`{"date": "2019-12-01", "pricesDate": "2019-12-21", "version": "4.6.1+20191221"}`

`date` should be `2019-12-04` (see https://mtgjson.com/changelog/#_4-6-1)

**Comment by tooomm** [comment]
🙈 

As of 31th december...

- on page header: `20191229`
![date](https://user-images.githubusercontent.com/9874850/71619728-0c69ca00-2bc6-11ea-874c-627c057abfb2.png)

- in [version.json](https://www.mtgjson.com/files/version.json) file: `20191227`
`{"date": "2019-12-01", "pricesDate": "2019-12-27", "version": "4.6.1+20191227"}`

**Comment by ZeldaZach** [comment]
Try hard refreshing. It is correct on my screen.

**Comment by tooomm** [comment]
Well, the "priceDate" updated... the "date" is still wrong and both show the same value again:
`{"date": "2019-12-29", "pricesDate": "2019-12-29", "version": "4.6.1+20191229"}`

**Comment by tooomm** [comment]
As of 13th of janaury:
`{"date": "2019-12-01", "pricesDate": "2020-01-08", "version": "4.6.1+20200108"}`
Where is that "date" coming from... we are back to https://github.com/mtgjson/mtgjson/issues/487#issuecomment-562900795 again.

How can the "date" (=["When all files were last completely built."](https://mtgjson.com/)) be older than the last version release?
I expect that on a new version release a new build is happening, too... so either the date is wrong in the version field (should be 2019-12-04), or the release date is wrong in the changelog on the webpage (should be 2019-12-01?). [See changelog for 4.6.1](https://mtgjson.com/changelog/#_4-6-1)

---

Edit: Ctrl+F5 finally brought me an update for version.json in between, took a while.
While "pricesDate" seems ok, the reported problem persists and the "date" field still shows "2019-12-01":
`{"date": "2019-12-01", "pricesDate": "2020-01-13", "version": "4.6.1+20200113"}`
