### ISSUE TITLE
Masters 25 missing 'booster' field

### ISSUE THREAD

**Issue by mildmongrel** [mtgjson/mtgjson#563]
In the latest version (3.14) of AllSets.json, the Masters 25 set is missing the "booster" field.

**Comment by ZeldaZach** [comment]
I swear I fixed this... Blah

**Comment by ZeldaZach** [comment]
Looking at the specs it should be there... will rebuild master soon

**Comment by tooomm** [comment]
A25.json here in the repo on master (https://github.com/mtgjson/mtgjson/blob/master/json/A25.json) and at mtgjson.com are still missing that value.
